FROM fedora:VER

COPY ssh /ssh

# Create non-root user USER
RUN \
    dnf update --nogpgcheck -y && \
    dnf install --nogpgcheck -y sudo openssh openssh-clients iputils net-tools which file hostname && \
    groupadd -g 1000 USER  && \
    useradd -g 1000 -u 1000 -m USER && \
    echo "USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/USER && \
    mv /ssh /home/USER/.ssh && \
    chown -R USER:USER /home/USER/.ssh
